"""Initial schema

Revision ID: f75b5bfb435c
Revises: 
Create Date: 2026-06-26 16:09:31.909337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75b5bfb435c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('wid', sa.String(), nullable=False),
    sa.Column('ean', sa.String(), nullable=False),
    sa.Column('manufacturing_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('wid')
    )
    op.create_index(op.f('ix_products_wid'), 'products', ['wid'], unique=True)
    op.create_table('verification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wid', sa.String(), nullable=False),
    sa.Column('checked_by', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wid'], ['products.wid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_logs_checked_at'), 'verification_logs', ['checked_at'], unique=False)
    op.create_index(op.f('ix_verification_logs_wid'), 'verification_logs', ['wid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_logs_wid'), table_name='verification_logs')
    op.drop_index(op.f('ix_verification_logs_checked_at'), table_name='verification_logs')
    op.drop_table('verification_logs')
    op.drop_index(op.f('ix_products_wid'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
